### PR TITLE
fix(VLE): Update account menu scores on node status changes

### LINKED ISSUE #971: Student account menu scores do not update
## Description
The student account menu score display no longer updates while unit is open. It only calculates total score and percentage when first loaded.

It should update whenever a new auto-score or teacher score is received.

Image

### PR DESCRIPTION
**Pull request by breity**
## Changes
Adds a subscription in StudentAccountMenu to `studentDataService.nodeStatusesChanged$`. Updates scores on each change.

Note that the account menu score displays do not update in real time when a new teacher score annotation is added. Student needs to navigate to a new step or submit some work for the scores to update. This should probably be fixed in a separate issue relating to websocket messages.

Resolves #971.

## Test
1. Launch a unit with a c-rater auto-scored item in preview mode.
2. Submit a response to the c-rater item.
3. Check that total score and score % update in the student account menu.
4. Launch a run with a c-rater item as a student.
5. Submit a response to the c-rater item.
6. Check that total score and score % update in the student account menu.
7. As a teacher, create a new score annotation for any component in the run.
8. As the student, navigate to a new step or submit some work.
9. Check that total score and score % update in the student account menu.

### CODE REVIEW

File: src/assets/wise5/vle/student-account-menu/student-account-menu.component.ts [hunk 1]
```diff
@@ -43,11 +45,26 @@ export class StudentAccountMenuComponent implements OnInit {
...
     this.usersInWorkgroup = this.configService.getUsernamesByWorkgroupId(this.workgroupId);
+    this.usernamesDisplay = this.getUsernamesDisplay(this.usersInWorkgroup);
+    this.updateScores();
+    if (this.maxScore != null) {
+      this.subscriptions.add(
+        this.studentDataService.nodeStatusesChanged$.subscribe(() => {
+          this.updateScores();
+        })
+      );
+    }
```
Comment (hirokiterashima) [inline src/assets/wise5/vle/student-account-menu/student-account-menu.component.ts]: What is the maxScore null check for? Don't we want the scores to update even if maxScore is null?

Comment (breity) [reply src/assets/wise5/vle/student-account-menu/student-account-menu.component.ts]: We only show scores in the template if maxScore is not null. I refactored based on our discussion.

**Review by hirokiterashima — APPROVED** [review]
LGTM
