### PR TITLE
Data Explorer fixed axis

### LINKED ISSUE #14: Data Explorer fixed axis
Allow authors of a Data Explorer component to fix an axis to use a specific column in the table. For example the author may always want the X Axis to use the first column in the table but allow the student to choose the second or third column for the Y Axis. Allow any or all axes (X Axis, Y Axis 1, Y Axis 2, etc.) to be fixed by the author.

### PR DESCRIPTION
**Pull request by geoffreykwan**
Enable Data Explorer in a Table component and choose which table columns to use for the x or y data. Make sure it works in the Authoring, Student, and Grading views.

Try these scenarios
- only X Data has a specified table column
- only Y Data has a specified table column
- X Data and Y Data have specified table columns
- using "Number of Series" greater than 1

Closes #14

### CODE REVIEW

File: src/assets/wise5/components/table/tableController.ts [hunk 1]
```diff
@@ -276,12 +297,68 @@ class TableController extends ComponentController {
...
-    }
+    this.dataExplorerYAxisLabels = Array(this.componentContent.numDataExplorerYAxis).fill('');
     this.dataExplorerSeriesParams = this.componentContent.dataExplorerSeriesParams;
   }
 
+  setDataExplorerFixedAxisToColumn(): void {
+    for (
+      let dataExplorerSeriesIndex = 0;
+      dataExplorerSeriesIndex < this.dataExplorerSeries.length;
+      dataExplorerSeriesIndex++
```
Comment (hirokiterashima) [inline src/assets/wise5/components/table/tableController.ts]: Nit: I think we should just use i instead of dataExplorerSeriesIndex. It makes the code shorter and easier to read. What do you think?

File: src/assets/wise5/components/table/tableController.ts [hunk 2]
```diff
@@ -276,12 +297,68 @@ class TableController extends ComponentController {
...
+      if (yColumn != null) {
+        this.dataExplorerSeries[dataExplorerSeriesIndex].yColumn = yColumn;
+        this.dataExplorerSeries[dataExplorerSeriesIndex].name = this.columnNames[yColumn];
+        this.setDataExplorerYColumnIsDisabled(dataExplorerSeriesIndex + 1);
+      }
+    }
+  }
+
+  isAllDataExplorerSeriesSpecified(): boolean {
+    for (const singleDataExplorerSeries of this.dataExplorerSeries) {
```
Comment (hirokiterashima) [inline src/assets/wise5/components/table/tableController.ts]: Nit: I think we should just use series here instead of singleDataExplorerSeries. It makes the code shorter and easier to read. What do you think?

File: src/assets/wise5/components/table/tableController.ts [hunk 3]
```diff
@@ -1123,6 +1204,14 @@ class TableController extends ComponentController {
     }
   }
 
+  updateDataExplorerSeriesNames() {
+    for (const singleDataExplorerSeries of this.dataExplorerSeries) {
```
Comment (hirokiterashima) [inline src/assets/wise5/components/table/tableController.ts]: Nit: I think we should just use series here instead of singleDataExplorerSeries. It makes the code shorter and easier to read. What do you think?

File: src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.ts [hunk 4]
```diff
@@ -45,6 +49,21 @@ class EditTableAdvancedController extends EditAdvancedComponentAngularJSControll
     }
   }
 
+  getNumTableColumns(componentContent: any): number {
+    const tableData = componentContent.tableData;
+    const firstRow = tableData[0];
+    return firstRow.length;
```
Comment (hirokiterashima) [inline src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.ts]:
```suggestion
    return componentContent.tableData[0].length;
```

**Review by hirokiterashima — CHANGES_REQUESTED** [review]
Functionality looks good. See my code comments inline. Some are nit picky (marked 'nit'), so I'll leave it to you to change or not.

File: src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.ts [hunk 5]
```diff
@@ -45,6 +49,21 @@ class EditTableAdvancedController extends EditAdvancedComponentAngularJSControll
...
+  }
+
+  getColumnNames(componentContent: any): string[] {
+    const columnNames: string[] = [];
+    const firstRow = componentContent.tableData[0];
+    for (const cell of firstRow) {
+      columnNames.push(cell.text);
+    }
+    return columnNames;
```
Comment (hirokiterashima) [inline src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.ts]:
```suggestion
    const firstRow = componentContent.tableData[0];
    return firstRow.map((cell) => {
      return cell.text;
    })
```

**Review by breity — CHANGES_REQUESTED** [review]
Looking good for the most part. A couple issues:
1. The axis label for a fixed column is blank and can only be changed by typing in a value if "Can Student Edit Axis Labels" is true. If that is set to false, there will be no label for the axis. We should default to the column header.
2. ~~The series and axis colors don't match when there are multiple axes and series set.~~ Regression lines are a different color than their corresponding series for scatterplots with multiple y-axes + series. (Maybe this isn't related to the PR?)
image

File: src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.html [hunk 6]
```diff
@@ -111,6 +111,32 @@
           {{ ::'table.canStudentEditAxisLabels' | translate }}
         </md-checkbox>
       </div>
+      <div>
+        <p>Fix Data to Table Column <span><md-icon>help</md-icon><md-tooltip style="height: auto" md-direction="right">You can author x or y data to always use a specific table column.<br/>The student will not be able to change the table column for that<br/>x or y data. If you want the student to be able to choose the table<br/>column, you can leave the select option blank for that x or y data.</md-tooltip></span></p>
```
Comment (breity) [inline src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.html:115]: The text here (and in some other places) isn't translatable. Maybe we could wait until this is upgraded to Angular to add `i18n` attributes?

**Review by breity — APPROVED** [review]
Looks good!

**Review by hirokiterashima — APPROVED** [review]

**Comment by hirokiterashima** [comment]
Tested against production.
