### PR TITLE
fix(Manage Students): Student can end up in multiple workgroups

### LINKED ISSUE #1437: fix(Manage Students): Student can end up in multiple workgroups
Method 1 to reproduce the problem
1. Open the Manage Students view for a run in two different tabs
2. In tab 1 move a student (example aa0101) to another workgroup (example Team 101)
3. In tab 2 move the same student (example aa0101) to another different workgroup (example Team 102)
4. The student aa0101 will now be in Team 101 and Team 102

Method 2 to reproduce the problem
1. Open the Manage students view for a run
2. Click "New Team" and add a student (example aa0101) to the new team and click "Create" and then "Proceed". It will say "New Team 103 has been created." but it will not show Team 103 and aa0101 will still be in their original team.
3. Drag aa0101 to an existing team (example Team 102)
4. The student aa0101 will now be in Team 102 and Team 103

### PR DESCRIPTION
**Pull request by geoffreykwan**
## Changes

- Move student to another workgroup request only sends the to workgroup id now. It no longer sends the from workgroup id or the period id because it no longer needs it. The server will remove the student from all workgroups in the run and figure out the period by looking at the to workgroup.
- Requests to move student or create new workgroup now handles errors from the server

## Test

- Test with https://github.com/WISE-Community/WISE-API/pull/239

Test 1
1. Open the Manage Students view for a run in two different tabs
2. In tab 1 move a student (example aa0101) to another workgroup (example Team 101)
3. In tab 2 move the same student (example aa0101) to another different workgroup (example Team 102)
4. Refresh the page
5. The student aa0101 used to end up in Team 101 and Team 102 but now it should only end up in Team 102

Test 2
1. Open the Manage students view for a run
2. Click "New Team" and add a student (example aa0101) to the new team and click "Create" and then "Proceed". It will say "New Team 103 has been created." but it will not show Team 103. aa0101 will still be in their original team.
3. Drag aa0101 to an existing team (example Team 102)
4. Refresh the page
5. The student aa0101 used to end up in Team 102 and Team 103 but now should only end up in Team 102

Closes #1437

### CODE REVIEW

File: src/app/services/updateWorkgroupService.ts [hunk 1]
```diff
@@ -1,15 +1,10 @@
...
-import { TeacherDataService } from '../../assets/wise5/services/teacherDataService';
 
 @Injectable()
 export class UpdateWorkgroupService {
-  constructor(
-    private ConfigService: ConfigService,
-    private TeacherDataService: TeacherDataService,
-    private http: HttpClient
-  ) {}
+  constructor(private ConfigService: ConfigService, private http: HttpClient) {}
```
Comment (hirokiterashima) [inline src/app/services/updateWorkgroupService.ts]: Lower-case ConfigService?

File: src/app/services/updateWorkgroupService.ts [hunk 2]
```diff
@@ -18,18 +13,11 @@ export class UpdateWorkgroupService {
    * @param workgroupIdTo Workgroup ID to move student to. -1 if moving student to unassigned
    * @param periodId Period ID the student is in.
    */
-  moveMember(
-    userId: number,
-    workgroupIdFrom: number = -1,
-    workgroupIdTo: number = -1,
-    periodId: number = this.TeacherDataService.getCurrentPeriodId()
-  ) {
+  moveMember(userId: number, workgroupIdTo: number) {
```
Comment (hirokiterashima) [inline src/app/services/updateWorkgroupService.ts]: Update function comment to reflect new prams?
Add return signature?

**Review by hirokiterashima — APPROVED** [review]
Looks good. Ideally the Manage Students page would show the newly created workgroup right away. I'll write up a new issue.

Before merge, can you address my inline comments and also update messages.xlf?
